# -*- coding: utf-8 -*-
"""MajorProject1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ARXpWndQO2PhRmjfO0PrXPfjujZxFCXU
"""

!pip install wavefile
import matplotlib.pyplot as plt
import numpy as np
from numpy.core.fromnumeric import size
from scipy.io import loadmat
from scipy.io.wavfile import write
import wavefile
import csv
import pandas as pd


def plot(h1,s1,convolved_speech_data1,h2,s2,convolved_speech_data2,mixed_signal) :
  plt.subplot(3,1,1)
  plt.subplots_adjust(hspace=1,wspace=5)
  plt.title('Room Filter-1')
  plt.plot(np.arange(0,80000),h1[:80000])
  plt.subplot(3,1,2)
  plt.title('Raw Source-1')
  plt.plot(s1)
  plt.subplot(3,1,3)
  plt.title('Convolved Source-1 with Filter-1')
  plt.plot(convolved_speech_data1)
  plt.savefig('/content/drive/MyDrive/MajorProject/signal1.png')
  plt.close()


  plt.subplot(3,1,1)
  plt.subplots_adjust(hspace=1,wspace=5)
  plt.title('Room Filter-1')
  plt.plot(np.arange(0,80000),h2[:80000])
  plt.subplot(3,1,2)
  plt.title('Raw Source-1')
  plt.plot(s2)
  plt.subplot(3,1,3)
  plt.title('Convolved Source-1 with Filter-1')
  plt.plot(convolved_speech_data2)
  plt.savefig('/content/drive/MyDrive/MajorProject/signal2.png')
  plt.close()

  
  plt.plot(mixed_signal)
  plt.title('Mixed Source-1 and Source-2')
  plt.savefig('/content/drive/MyDrive/MajorProject/mixedsignal.png')
  plt.close()


mat1 = loadmat('/content/drive/MyDrive/MajorProject/45.mat')
h1 = mat1['impulse_response'][:,0]
fs1, s1 = wavefile.load('/content/drive/MyDrive/MajorProject/1_0a139a.wav')
s1=np.reshape(s1,s1.size)
convolved_speech_data1 = np.convolve(s1[:80000],h1[:5000])


mat2 = loadmat('/content/drive/MyDrive/MajorProject/135.mat')
fs2, s2 = wavefile.load('/content/drive/MyDrive/MajorProject/1_00bdad.wav')
s2=np.reshape(s2,s2.size)
h2 = mat2['impulse_response'][:,0]
convolved_speech_data2 = np.convolve(s2[:80000],h2[:5000])

#plotting and storing a sample signal
mixed_signal = convolved_speech_data1+convolved_speech_data2
#plot(h1,s1,convolved_speech_data1,h2,s2,convolved_speech_data2,mixed_signal)   


#creating the dataset
dataset={}
for k1 in np.arange(0.0,1.02,0.02):
  for k2 in np.arange(0.0,1.02,0.02):
    mixed_signal = (k1*convolved_speech_data1) + (k2*convolved_speech_data2)
    if k1==0 or k2==0:
      #write('/content/drive/MyDrive/MajorProject/custom_dataset/'+'1_'+str(k1)+'_'+str(k2)+'.wav',fs2,mixed_signal.astype(np.float32))
      dataset['1_'+str(round(k1,2))+'_'+str(round(k2,2))]=mixed_signal
    else:
      #write('/content/drive/MyDrive/MajorProject/custom_dataset/'+'2_'+str(k1)+'_'+str(k2)+'.wav',fs2,mixed_signal.astype(np.float32))
      dataset['2_'+str(round(k1,2))+'_'+str(round(k2,2))]=mixed_signal

df=pd.DataFrame.from_dict(dataset)
df.to_csv('/content/drive/MyDrive/MajorProject/dataset.csv')